### ISSUE TITLE
temporary stamps not deleted

### ISSUE THREAD

**Issue by jacob1** [ThePowderToy/tptmp#15]
When using TPTMP, you get a lot of "corrupted" stamps in the stamp browser, because it creates stamps and then deletes the file without deleting the stamp.

**Comment by handicraftsman** [comment]
True, it's after update to 91.2 (as i know)

**Comment by jacob1** [comment]
No, it has always done this. In 91.0 I modified the stamp browser to say "Error loading stamp" for these stamps. It used to just not fill the entire page, with no mention that some of the stamps were corrupted or ability to delete these stamps.

**Comment by gfgurhgtru** [comment]
jacob1 you tracker...

**Comment by jacob1** [comment]
?????

**Comment by jacob1** [comment]
Fixed in the next version of tpt, the bug was in there, not tptmp.
